server:
  port: 8050

spring:
  data:
    redis:
      host: localhost
      port: 6379
      maximum-active-connections-to-redis-instance: 30
      number-of-connections-to-keep-in-idle-state: 10
      minimum-number-of-idle-connections-in-the-pool: 2
      test-the-connection-before-borrowing-from-the-pool: true
      test-the-connection-before-returning-to-the-pool: true